# Generated by Django 4.2 on 2026-03-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Akt',
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'managed': False, 'verbose_name': 'Табличная часть документа', 'verbose_name_plural': 'Табличная часть документов'},
        ),
        migrations.AlterModelOptions(
            name='fio',
            options={'verbose_name': 'Подотчетное лицо', 'verbose_name_plural': 'Подотчетные лица'},
        ),
    ]
