# Generated by Django 4.2 on 2026-03-02 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_akt_alter_detail_options_alter_fio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='fio',
            options={'managed': False, 'verbose_name': 'Подотчетное лицо', 'verbose_name_plural': 'Подотчетные лица'},
        ),
    ]
