# Generated by Django 4.2 on 2026-03-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_doc_options_alter_fio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='datadoc_temp',
            field=models.DateField(blank=True, null=True),
        ),

    ]
