# Generated by Django 4.2 on 2026-03-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0004_doc_datadoc_temp_doc_fio_doc_obct_doc_postav_and_more'),
    ]

    operations = [
        # Переименовываем старое поле datadoc (строковое) в datadoc_old
        migrations.RenameField(
            model_name='doc',
            old_name='datadoc',
            new_name='datadoc_old',
        ),

        # Переименовываем datadoc_temp (DateField) в datadoc
        migrations.RenameField(
            model_name='doc',
            old_name='datadoc_temp',
            new_name='datadoc',
        ),

        # Удаляем старое поле
        migrations.RemoveField(
            model_name='doc',
            name='datadoc_old',
        ),

        # Если есть другие изменения полей, оставьте их
        migrations.AlterField(
            model_name='doc',
            name='nomer',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='oper',
            field=models.IntegerField(verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итого'),
        ),
    ]